name: account_abstraction_alchemy
description: "Account Abstraction smart wallet client for Alchemy, only supports usage with gas manager"
version: 0.1.6
homepage: https://wormfare.com/
repository: https://github.com/wormfare/account-abstraction-alchemy
issue_tracker: https://github.com/wormfare/account-abstraction-alchemy/issues

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.0.0"

platforms:
  android:
  ios:
  web:

topics:
  - wallets
  - ethereum
  - web3
  - account-abstraction
  - alchemy

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  asn1lib: ^1.5.2
  blockchain_utils: ^2.1.2
  web3dart_builders: ^0.1.2
  web3dart: ^2.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
